### ISSUE TITLE
task list 2017/05/25

### ISSUE THREAD

**Issue by takahasi** [gbiggs/ros_moveit_rsj_tutorial#2]
Items to be modified ... note to self.

## linux_and_ros_install
- [x] Live USB を作成する PC と，Ubuntu をインストールする PC が別でも構わないことを記載した方が良いかも
- [x] ROS Kinetic の Ubuntu インストール方法も分岐点が多いので，代表的な方法（コマンド）を転記した方が良いかも
- [x] 全てのインストールが完了しているかどうか確認する方法の記載が欲しい

## manipulator_check
- [x] ./servo_check に sudo もしくは /dev のパーミッション変更が必要

## ros_basics
- [x] displayer を実行する前にもう一度 catkin_make をしているのはなぜ？
- [x] CMakeLists.txt の編集位置を行数付きで表示した方が良さそう
- [x] 作成する config, launch ディレクトリのパスを記載した方が良さそう

**Comment by gbiggs** [comment]
Fixed by 852aa0437978dc78f65a84da030dddc84461545d, 00f492a859d5f7a89d7bfd36b3e6ba9ebebdb1bc, c8608967790786176a8195c90c1734cf38075fbe, and 1157e0b478e7e4a4a11d7d6f0d052dc286881c15
